# Generated by Django 4.2.5 on 2023-10-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test_match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('talent', models.CharField(max_length=25)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ttwenty_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('talent', models.CharField(max_length=25)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
